version: '3.8'

services:
  word-mcp-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: linux-base
    ports:
      - "8000:8000"
    environment:
      - MCP_TRANSPORT=http
      - HOST=0.0.0.0
      - PORT=8000
    command: ["word_docx_tools", "--transport", "http", "--host", "0.0.0.0", "--port", "8000"]

  word-mcp-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: linux-base
    ports:
      - "8000:8000"
    environment:
      - MCP_TRANSPORT=http
      - HOST=0.0.0.0
      - PORT=8000
    command: ["word_docx_tools", "--transport", "http", "--host", "0.0.0.0", "--port", "8000"]
    restart: unless-stopped

  # Windows container variant (requires Windows host)
  # Uncomment this section if deploying on Windows with Docker Desktop
  # word-mcp-windows:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #     target: windows-base
  #   environment:
  #     - MCP_TRANSPORT=stdio
  #   # Windows containers require special configuration for COM objects
  #   # This is a template - actual deployment may require additional setup

# Volumes for persistent data (if needed)
volumes:
  # Example volume for document storage
  # documents:
  #   driver: local