name: Code Quality CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  code-quality:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install black isort mypy pytest
      - name: Check formatting with Black
        run: black --check word_document_server
      - name: Check import order with isort
        run: isort --check-only word_document_server
      - name: Static type checking with mypy
        run: mypy word_document_server
      - name: Run tests with pytest
        run: pytest